### ISSUE TITLE
some suggesions

### ISSUE THREAD

**Issue by kid1412621** [jchomarat/wttop#1]
1. support system time(for full-screen purpose)
2. allow to adjust the layout

**Comment by jchomarat** [comment]
Hello @kid1412621 ,

Thanks for your input. Adding the system time is a good idea, and quite simple - I'll add that the backlog (no ETA yet)

Regarding adjusting the layout, it will be trickier. I will dig up a little bit.

Cheers

**Comment by kid1412621** [comment]
@jchomarat good to hear. and if possible to install via `Install-Module`

**Comment by jchomarat** [comment]
Actually I was planning on adding it to Scoop (https://scoop.sh/). I will look into Install-Module also

**Comment by kid1412621** [comment]
Cool, i'm using scoop too.
