### ISSUE TITLE
Process List is Empty

### ISSUE THREAD

**Issue by graphixillusion** [jchomarat/wttop#8]
Hi there. Version 1.1 used. The Processes List is empty, even if you launch as administrator.

**Comment by jchomarat** [comment]
Hello, on what Windows' version you are?

**Comment by graphixillusion** [comment]
@jchomarat Windows 10 1909, sorry didn't say that before...

**Comment by jchomarat** [comment]
I am on 19041 ... can you see the other widgets (CPU/RAM etc ...)? 
What terminal are you using? (CMD, PowerShell/PowerShell core terminal/Windows Terminal)?

**Comment by graphixillusion** [comment]
Tryed it with: CMD, Powershell and Windows Terminal, same result with all of them. I can see CPU & Memory, Network and Disk; the list of processes is empty. 

I have more hard drives connected to this system but as you can see from the screenshot, only three of them are listed

**Comment by jchomarat** [comment]
Ok thanks, let me investigate!

**Comment by jchomarat** [comment]
Ok, I am sorry for getting back month after, but I cannot reproduce after many tests.
I am closing this ticket

Thanks
