### ISSUE TITLE
Terminal is messed up if you resize while running wttop

### ISSUE THREAD

**Issue by ascarter** [jchomarat/wttop#9]
* Launch terminal with default window size
* Launch wttop
* Resize window vertically
* Quit
* Terminal is messed up and won't redraw correctly for the expanded part

This could be in the underlying text UI library, not your code.

![image](https://user-images.githubusercontent.com/4931/96908484-8fa82500-1451-11eb-8a7e-7e71511b9db7.png)

**Comment by jchomarat** [comment]
Hello @ascarter ,

I can indeed reproduce. I am wondering if it does not come from the Windows Terminal actually ...
Let me dig up further - maybe there is something I can when quitting to redraw correctly the window. I will also open a ticket on the underlying library (Terminal.Gui).

**Comment by jchomarat** [comment]
I have tried it on regular cmd and powershell consoles, and the issue is not present. So it looks like it comes from the Windows Terminal.
I have, just in case, upgraded the underlying UI library, same thing (but too many breaking changes, so I won't update yet this app)
